/* Generated by Yosys 0.26+53 (git sha1 8216b23fb, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1677343603595/work=/usr/local/src/conda/yosys-0.26_54_g8216b23fb -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

module decoder4x16_w_clk(clk, in, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input clk;
  wire clk;
  input [3:0] in;
  wire [3:0] in;
  wire \inp_reg[0] ;
  wire \inp_reg[1] ;
  wire \inp_reg[2] ;
  wire \inp_reg[3] ;
  output [0:15] out;
  wire [0:15] out;
  wire \outp_reg[0] ;
  wire \outp_reg[10] ;
  wire \outp_reg[11] ;
  wire \outp_reg[12] ;
  wire \outp_reg[13] ;
  wire \outp_reg[14] ;
  wire \outp_reg[15] ;
  wire \outp_reg[1] ;
  wire \outp_reg[2] ;
  wire \outp_reg[3] ;
  wire \outp_reg[4] ;
  wire \outp_reg[5] ;
  wire \outp_reg[6] ;
  wire \outp_reg[7] ;
  wire \outp_reg[8] ;
  wire \outp_reg[9] ;
  sky130_fd_sc_hd__buf_1 _15_ (
    .A(\inp_reg[1] ),
    .X(_00_)
  );
  sky130_fd_sc_hd__buf_1 _16_ (
    .A(\inp_reg[0] ),
    .X(_01_)
  );
  sky130_fd_sc_hd__and4_2 _17_ (
    .A(_00_),
    .B(_01_),
    .C(\inp_reg[2] ),
    .D(\inp_reg[3] ),
    .X(_02_)
  );
  sky130_fd_sc_hd__buf_1 _18_ (
    .A(_02_),
    .X(\outp_reg[15] )
  );
  sky130_fd_sc_hd__buf_1 _19_ (
    .A(\inp_reg[2] ),
    .X(_03_)
  );
  sky130_fd_sc_hd__and4b_2 _20_ (
    .A_N(_01_),
    .B(_03_),
    .C(\inp_reg[3] ),
    .D(\inp_reg[1] ),
    .X(_04_)
  );
  sky130_fd_sc_hd__buf_1 _21_ (
    .A(_04_),
    .X(\outp_reg[14] )
  );
  sky130_fd_sc_hd__and4b_2 _22_ (
    .A_N(_00_),
    .B(\inp_reg[0] ),
    .C(\inp_reg[2] ),
    .D(\inp_reg[3] ),
    .X(_05_)
  );
  sky130_fd_sc_hd__buf_1 _23_ (
    .A(_05_),
    .X(\outp_reg[13] )
  );
  sky130_fd_sc_hd__and4bb_2 _24_ (
    .A_N(_00_),
    .B_N(_01_),
    .C(\inp_reg[2] ),
    .D(\inp_reg[3] ),
    .X(_06_)
  );
  sky130_fd_sc_hd__buf_1 _25_ (
    .A(_06_),
    .X(\outp_reg[12] )
  );
  sky130_fd_sc_hd__buf_1 _26_ (
    .A(\inp_reg[3] ),
    .X(_07_)
  );
  sky130_fd_sc_hd__and4b_2 _27_ (
    .A_N(_03_),
    .B(_07_),
    .C(\inp_reg[1] ),
    .D(\inp_reg[0] ),
    .X(_08_)
  );
  sky130_fd_sc_hd__buf_1 _28_ (
    .A(_08_),
    .X(\outp_reg[11] )
  );
  sky130_fd_sc_hd__and4bb_2 _29_ (
    .A_N(_01_),
    .B_N(_03_),
    .C(\inp_reg[3] ),
    .D(\inp_reg[1] ),
    .X(_09_)
  );
  sky130_fd_sc_hd__buf_1 _30_ (
    .A(_09_),
    .X(\outp_reg[10] )
  );
  sky130_fd_sc_hd__and4bb_2 _31_ (
    .A_N(_00_),
    .B_N(_03_),
    .C(\inp_reg[3] ),
    .D(\inp_reg[0] ),
    .X(_10_)
  );
  sky130_fd_sc_hd__buf_1 _32_ (
    .A(_10_),
    .X(\outp_reg[9] )
  );
  sky130_fd_sc_hd__nor4b_2 _33_ (
    .A(_00_),
    .B(_01_),
    .C(_03_),
    .D_N(_07_),
    .Y(\outp_reg[8] )
  );
  sky130_fd_sc_hd__and4b_2 _34_ (
    .A_N(_07_),
    .B(\inp_reg[2] ),
    .C(\inp_reg[0] ),
    .D(\inp_reg[1] ),
    .X(_11_)
  );
  sky130_fd_sc_hd__buf_1 _35_ (
    .A(_11_),
    .X(\outp_reg[7] )
  );
  sky130_fd_sc_hd__and4bb_2 _36_ (
    .A_N(_01_),
    .B_N(_07_),
    .C(\inp_reg[2] ),
    .D(\inp_reg[1] ),
    .X(_12_)
  );
  sky130_fd_sc_hd__buf_1 _37_ (
    .A(_12_),
    .X(\outp_reg[6] )
  );
  sky130_fd_sc_hd__and4bb_2 _38_ (
    .A_N(_00_),
    .B_N(_07_),
    .C(\inp_reg[2] ),
    .D(\inp_reg[0] ),
    .X(_13_)
  );
  sky130_fd_sc_hd__buf_1 _39_ (
    .A(_13_),
    .X(\outp_reg[5] )
  );
  sky130_fd_sc_hd__nor4b_2 _40_ (
    .A(_00_),
    .B(_01_),
    .C(_07_),
    .D_N(_03_),
    .Y(\outp_reg[4] )
  );
  sky130_fd_sc_hd__and4bb_2 _41_ (
    .A_N(_03_),
    .B_N(_07_),
    .C(\inp_reg[1] ),
    .D(\inp_reg[0] ),
    .X(_14_)
  );
  sky130_fd_sc_hd__buf_1 _42_ (
    .A(_14_),
    .X(\outp_reg[3] )
  );
  sky130_fd_sc_hd__nor4b_2 _43_ (
    .A(_01_),
    .B(_03_),
    .C(_07_),
    .D_N(_00_),
    .Y(\outp_reg[2] )
  );
  sky130_fd_sc_hd__nor4b_2 _44_ (
    .A(_00_),
    .B(_03_),
    .C(_07_),
    .D_N(_01_),
    .Y(\outp_reg[1] )
  );
  sky130_fd_sc_hd__nor4_2 _45_ (
    .A(_00_),
    .B(_01_),
    .C(_03_),
    .D(_07_),
    .Y(\outp_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _46_ (
    .CLK(clk),
    .D(\outp_reg[15] ),
    .Q(out[15])
  );
  sky130_fd_sc_hd__dfxtp_2 _47_ (
    .CLK(clk),
    .D(\outp_reg[14] ),
    .Q(out[14])
  );
  sky130_fd_sc_hd__dfxtp_2 _48_ (
    .CLK(clk),
    .D(\outp_reg[13] ),
    .Q(out[13])
  );
  sky130_fd_sc_hd__dfxtp_2 _49_ (
    .CLK(clk),
    .D(\outp_reg[12] ),
    .Q(out[12])
  );
  sky130_fd_sc_hd__dfxtp_2 _50_ (
    .CLK(clk),
    .D(\outp_reg[11] ),
    .Q(out[11])
  );
  sky130_fd_sc_hd__dfxtp_2 _51_ (
    .CLK(clk),
    .D(\outp_reg[10] ),
    .Q(out[10])
  );
  sky130_fd_sc_hd__dfxtp_2 _52_ (
    .CLK(clk),
    .D(\outp_reg[9] ),
    .Q(out[9])
  );
  sky130_fd_sc_hd__dfxtp_2 _53_ (
    .CLK(clk),
    .D(\outp_reg[8] ),
    .Q(out[8])
  );
  sky130_fd_sc_hd__dfxtp_2 _54_ (
    .CLK(clk),
    .D(\outp_reg[7] ),
    .Q(out[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _55_ (
    .CLK(clk),
    .D(\outp_reg[6] ),
    .Q(out[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _56_ (
    .CLK(clk),
    .D(\outp_reg[5] ),
    .Q(out[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _57_ (
    .CLK(clk),
    .D(\outp_reg[4] ),
    .Q(out[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _58_ (
    .CLK(clk),
    .D(\outp_reg[3] ),
    .Q(out[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _59_ (
    .CLK(clk),
    .D(\outp_reg[2] ),
    .Q(out[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _60_ (
    .CLK(clk),
    .D(\outp_reg[1] ),
    .Q(out[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _61_ (
    .CLK(clk),
    .D(\outp_reg[0] ),
    .Q(out[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _62_ (
    .CLK(clk),
    .D(in[0]),
    .Q(\inp_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _63_ (
    .CLK(clk),
    .D(in[1]),
    .Q(\inp_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _64_ (
    .CLK(clk),
    .D(in[2]),
    .Q(\inp_reg[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _65_ (
    .CLK(clk),
    .D(in[3]),
    .Q(\inp_reg[3] )
  );
endmodule
